import { Field } from "../components/FormComponent/FormComponent";

export const fieldsFinanceMoviment: Field[] = [
  {
    fieldname: "title",
    label: "Título",
    fieldtype: "text",
    required: true,
    placeholder: "Ex.: Pagamento assistência - João Lima",
    section: "Dados da movimentação",
  },
  {
    fieldname: "type",
    label: "Tipo de movimentação",
    fieldtype: "select",
    required: true,
    placeholder: "Selecione o tipo",
    options: ["in|Entrada", "out|Saída"],
    section: "Dados da movimentação",
  },
  {
    fieldname: "category",
    label: "Categoria",
    fieldtype: "select",
    placeholder: "Selecione a categoria",
    options: [
      "Serviço técnico|Serviço técnico",
      "Estoque|Estoque",
      "Software|Software",
      "Fixos|Fixos",
      "Marketing|Marketing",
      "Outros|Outros",
    ],
    section: "Dados da movimentação",
  },
  {
    fieldname: "value",
    label: "Valor",
    fieldtype: "number",
    required: true,
    placeholder: "Ex.: 280.00",
    section: "Dados da movimentação",
  },
  {
    fieldname: "date",
    label: "Data",
    fieldtype: "date",
    placeholder: "Ex.: 05/02/2026",
    section: "Dados da movimentação",
  },
  {
    fieldname: "status",
    label: "Status",
    fieldtype: "select",
    placeholder: "Selecione o status",
    options: ["Pago|Pago", "Pendente|Pendente", "Agendado|Agendado"],
    section: "Dados da movimentação",
  },
  {
    fieldname: "channel",
    label: "Canal",
    fieldtype: "select",
    placeholder: "Selecione o canal",
    options: [
      "PIX|PIX",
      "Cartao|Cartão",
      "Dinheiro|Dinheiro",
      "Boleto|Boleto",
      "Transferencia|Transferência",
    ],
    section: "Dados da movimentação",
  },
  {
    fieldname: "notes",
    label: "Observações",
    fieldtype: "textarea",
    placeholder: "Informações adicionais.",
    section: "Observações",
  },
  {
    fieldname: "comprovante",
    label: "Comprovante",
    fieldtype: "image",
    section: "Anexos",
  },
];
