import { Field } from "../components/FormComponent/FormComponent";

export const fieldsOrder: Field[] = [
  {
    fieldname: "cliente_id",
    label: "Cliente",
    fieldtype: "select",
    required: true,
    placeholder: "Selecione o cliente",
    section: "Cliente",
  },
  {
    fieldname: "cliente_contato",
    label: "Contato",
    fieldtype: "tel",
    placeholder: "Ex.: (11) 99999-0000",
    section: "Cliente",
  },
  {
    fieldname: "equipamento",
    label: "Equipamento",
    fieldtype: "text",
    placeholder: "Ex.: Notebook Dell Inspiron",
    section: "Equipamento",
  },
  {
    fieldname: "problema",
    label: "Descrição do problema",
    fieldtype: "textarea",
    placeholder: "Explique o que precisa ser feito.",
    section: "Equipamento",
  },
  {
    fieldname: "servico_id",
    label: "Serviço realizado",
    fieldtype: "select",
    placeholder: "Selecione o serviço",
    section: "Serviço",
  },
  {
    fieldname: "servico_descricao",
    label: "Descrição do serviço",
    fieldtype: "textarea",
    placeholder: "Detalhe o serviço quando não estiver selecionado.",
    section: "Serviço",
  },
  {
    fieldname: "valor_estimado",
    label: "Valor",
    fieldtype: "number",
    required: true,
    placeholder: "Ex.: 320.00",
    section: "Resumo",
  },
  {
    fieldname: "validade",
    label: "Validade",
    fieldtype: "text",
    placeholder: "Ex.: 10/03/2026",
    section: "Resumo",
  },
  {
    fieldname: "status",
    label: "Status",
    fieldtype: "select",
    placeholder: "Selecione o status",
    options: [
      "em_analise|Em análise",
      "aprovado|Aprovado",
      "recusado|Recusado",
    ],
    section: "Resumo",
  },
  {
    fieldname: "observacoes",
    label: "Observações",
    fieldtype: "textarea",
    placeholder: "Informações extras para o orçamento.",
    section: "Resumo",
  },
];
